### ISSUE TITLE
Something in the latest HA version 2026.8.1 broke Alarm.com integration

### ISSUE THREAD

**Issue by borkedporcupine** [ibasebcast/ha-alarmdotcom#92]
I was using the alarm.com integration this was forked from it broke after the last HA upgrade.  Installed this to see if it was more activly maintained, and it's also broken it appears.  I can't communicate with my panel.  Not sure which logs are relevant.  I was getting a 403 error on the other integration but I don't know which logs to provide here.  I don't see many logs but everything just says "unavailable" I do however see successful logins from the integration on my alarm.com account.  I'll be happy to provide anything helpful just let me know what you might need. 

```
Logger: homeassistant.components.alarm_control_panel
Source: helpers/entity_platform.py:725
Integration: Alarm control panel ([documentation](https://www.home-assistant.io/integrations/alarm_control_panel), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+alarm_control_panel%22))
First occurred: 11:04:07 AM (1 occurrence)
Last logged: 11:04:07 AM

Error adding entity alarm_control_panel.panel for domain alarm_control_panel with platform alarmdotcom

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 725, in _async_add_entities
    await self._async_add_entity(
        entity, False, entity_registry, config_subentry_id
    )
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1104, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1444, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/alarmdotcom/base_device.py", line 74, in async_added_to_hass
    self._update_device_data()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/alarmdotcom/base_device.py", line 106, in _update_device_data
    f"Updated {self.device_type_name} {self._friendly_name_internal()} ({self._adc_id}): {self.state}"
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AlarmControlPanel' object has no attribute '_friendly_name_internal'
``` 

and

```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:348
First occurred: 11:04:07 AM (3 occurrences)
Last logged: 11:04:07 AM

Detected that custom integration 'alarmdotcom' calls `device_registry.async_get_or_create` referencing a non existing `via_device` ('alarmdotcom', None), with device info: {'identifiers': {('alarmdotcom', '109092085-127')}, 'name': 'Panel', 'via_device': ('alarmdotcom', None), 'manufacturer': 'Alarm.com'} at custom_components/alarmdotcom/alarm_control_panel.py, line 50: async_add_entities(. This will stop working in Home Assistant 2025.12.0, please create a bug report at https://github.com/pyalarmdotcom/alarmdotcom/issues
Detected that custom integration 'alarmdotcom' calls `device_registry.async_get_or_create` referencing a non existing `via_device` ('alarmdotcom', None), with device info: {'identifiers': {('alarmdotcom', '109092085-127')}, 'name': 'Panel', 'via_device': ('alarmdotcom', None), 'manufacturer': 'Alarm.com'} at custom_components/alarmdotcom/binary_sensor.py, line 92: async_add_entities(. This will stop working in Home Assistant 2025.12.0, please create a bug report at https://github.com/pyalarmdotcom/alarmdotcom/issues
Detected that custom integration 'alarmdotcom' calls `device_registry.async_get_or_create` referencing a non existing `via_device` ('alarmdotcom', None), with device info: {'identifiers': {('alarmdotcom', '109092085-127')}, 'name': 'Panel', 'via_device': ('alarmdotcom', None), 'manufacturer': 'Alarm.com'} at custom_components/alarmdotcom/button.py, line 62: async_add_entities(. This will stop working in Home Assistant 2025.12.0, please create a bug report at https://github.com/pyalarmdotcom/alarmdotcom/issues
```

**Comment by ibasebcast** [comment]
Thanks for the detailed logs — this pinpoints the problem. The traceback shows custom_components/alarmdotcom/base_device.py, but that file doesn't exist in the current version of this integration (it was renamed to entity.py a while back). Also, the deprecation warning tells you to file a bug at github.com/pyalarmdotcom/alarmdotcom/issues — that's the original upstream repo, not this fork.

This strongly suggests you still have either the original alarmdotcom integration or a stale/old copy of this fork installed under custom_components/alarmdotcom, rather than a current install of ha-alarmdotcom. Since both share the same alarmdotcom folder name, HACS (or a manual copy) can leave old files in place if the old integration wasn't fully removed first.

Can you try:

Fully delete config/custom_components/alarmdotcom (back up first if you want).
In HACS, remove any existing "Alarm.com" custom repository entry, then re-add ibasebcast/ha-alarmdotcom fresh.
Restart HA and check the manifest version under Settings → Devices & Services → Alarm.com (it should read a 2026.7.x version).

That should clear up the _friendly_name_internal crash, which comes from very old code calling a private HA core method that no longer exists after HA's entity-naming migration.

**Comment by borkedporcupine** [comment]
OK I think i have this now.  Not 100% sure how this is fixed...I'm not sure if I somehow forgot to disable the old instance or what. However removed everything as instructed, deleted files, uninstalled, restarted, had to re-add the custom repository (apparently that gets removed if there aren't any active components?), restarted home assistant, then somehow the config was already active and I can talk to my panel I didn't need to re-sign in or anything.  

Regardless thanks for the help must have been something on my end with my process.  Glad to see an active maintainer, this integration has been very important and helpful to me.
